name: Deploy Demo

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to ByteInspire Cloud project
        id: byteinspire_cloud_project_deployer
        uses: ./
        with:
          service-id: "${{ secrets.SERVICE_ID }}"
          token: "${{ secrets.ACCESS_TOKEN }}"
          directory: "./demo"
          changelog: "deploy by action"

      - name: Check outputs
        run: |
          echo cloud_project_url ${{steps.byteinspire_cloud_project_deployer.outputs.cloud-project-url}}
          echo version ${{steps.byteinspire_cloud_project_deployer.outputs.version}}
